Enclave native TLS using Noise
marlinprotocol/oyster-sdk-rs pull request #9
Opened 2023-12-26 14:04 UTC by roshanr95

With optional attestation verification on both sides.

2023-12-27 07:38 UTC, vg-27 commented on examples/scallop.rs
> +    unsafe { crypto_sign_ed25519_sk_to_curve25519(sk.as_mut_ptr(), sign_sk.as_mut_ptr()) };
Just the read-only reference to sign_pk, sign_sk would be sufficient. `mut` not  required.

2023-12-27 07:38 UTC, vg-27 commented on examples/scallop.rs
> +        sleep(Duration::from_secs(1)).await;
maybe put this in for loop.

2023-12-27 07:38 UTC, vg-27 commented on src/scallop.rs
> +//   - Server can send the payload in the second message
`payload` -> `attestation`?

2023-12-27 07:38 UTC, vg-27 commented on src/scallop.rs
> +        stream.flush().await?;
DRY, can be converted to helper function.

2023-12-27 07:38 UTC, vg-27 commented on src/scallop.rs
> +    buf: Box<[u8]>,
`buf` -> `rbuf` ?

2023-12-27 07:38 UTC, vg-27 commented on src/scallop.rs
> +
should call flush before shut down?

2023-12-30 05:51 UTC, roshanr95 commented
@vg-27 comments resolved

2024-01-01 08:49 UTC, vg-27 requested changes
Checking more about AsyncWrite behavior wrt flushing. And scenarios around it.

2024-01-01 08:49 UTC, vg-27 commented on src/attestation.rs
> +            .ok_or(AttestationError::ParseFailed("pcr{i} not found".into()))?;
Need to use format here, otherwise error message will be `pcr{i}`. Into wont fill value of `i`. Similar to L121

2024-01-01 08:49 UTC, vg-27 commented on src/scallop.rs
> +) -> Result<usize, ScallopError> {
Implementation is not raising ScallopError as defined in result. Need to map error at L267, L270, L273.

2024-01-01 08:49 UTC, vg-27 commented on src/scallop.rs
> +) -> Result<(), ScallopError> {
Need to raise ScallopError explicitly.

2024-01-01 08:49 UTC, vg-27 commented on src/scallop.rs
> +        noise_buf: &mut [u8],
I think, `noise_buf` shouldn't be a input argument. It's just an internal buffer. Either use from the outer function scope or create new one within function.

2024-01-01 09:26 UTC, vg-27 commented on src/scallop.rs
> +        // TODO: Should we flush here so it does not need to be called in the common case?
Following spec seems reasonable to me:
1. User given buffer to write method should be encrypted only once.
2. This trait implementation doesn't require buffering, because in poll_write method, it encrypt the given user payload, and write it all to the base writer, and flush the base writer.
3. poll_flush will be no-op since base writer flush is being called in every write.
4. async nature of writer is still preserved while being able to send all data without loss.
5. Error handling: reraise all IO errors raised by base writer and don't keep the buffer of encrypted payload.

2024-01-01 13:52 UTC, roshanr95 commented on src/attestation.rs
> +            .ok_or(AttestationError::ParseFailed("pcr{i} not found".into()))?;
fixed

2024-01-01 13:54 UTC, roshanr95 commented on src/scallop.rs
> +) -> Result<usize, ScallopError> {
it's automatic, would not compile otherwise on mismatches

2024-01-01 13:54 UTC, roshanr95 commented on src/scallop.rs
> +) -> Result<(), ScallopError> {
it's automatic, would not compile otherwise on mismatches

2024-01-01 13:56 UTC, roshanr95 commented on src/scallop.rs
> +        noise_buf: &mut [u8],
the goal is to reuse buffers and not allocate again and again

in this case especially, we have to choose between the existing buffer and a new heap allocated buffer. Since the existing stack buffer is too small to hold attestations

2024-01-01 14:13 UTC, roshanr95 commented on src/scallop.rs
> +        // TODO: Should we flush here so it does not need to be called in the common case?
Here are the constraints:

1. The buffer given by the user needs to be encrypted before sending it to `poll_write`.
2. Once encrypted, either the buffer has to be sent across the wire, or the connection has to be abandoned. This is because messages are ordered by increasing nonce. Handling out of order messages is painful and potentially insecure, don't think we want to go down this road if at all possible.
3. Regardless, re-encrypting the same message twice won't give the same result (most likely purely because of nonce, but have to check).
4. base's `poll_write` might accept only part of the encrypted message, the rest has to be sent again in the next poll.

Given these, buffering seems to be unavoidable.

2024-01-01 14:14 UTC, roshanr95 commented on src/scallop.rs
> +        // TODO: Should we flush here so it does not need to be called in the common case?
In your spec, 2 is not guaranteed, base writer can accept partial messages as well...

2024-01-01 15:44 UTC, vg-27 approved these changes

2024-01-01 15:44 UTC, vg-27 commented on src/scallop.rs
> +        noise_buf: &mut [u8],
Okay, got it.

2024-01-01 15:44 UTC, vg-27 commented on src/scallop.rs
> +        // TODO: Should we flush here so it does not need to be called in the common case?
Okay, I understand, buffer is required for encrypted message. So, for now, users have to call flush at the end to ensure complete transfer.

2024-01-02 07:49 UTC, merged